### ISSUE TITLE
regression in machine learning

### ISSUE THREAD

**Issue by abhisek247767** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2023-MAKAUT-WB#1]
1. basic idea of  regression in ML?
2. Real life some example

That's all

**Comment by Giriraj-Roy** [comment]
Hello Sir,

I have gone through the repository and the given instructions. Being from an ML background it excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by abhisek247767** [comment]
@Giriraj-Roy

**Comment by Giriraj-Roy** [comment]
I was almost prepared with my regression file, which I definitely intended to be an markdown file.
But I see that in the repo you have already added a text file should I continue with it ?

I really think that a markdown file gives an extra edge to add some images, hence I vote for it naturally.

I will be waiting for the instructions.

**Comment by abhisek247767** [comment]
Ok..Do One thing create a new issue and heading that Linear Regression or Logistic regression  as your wish.as per your text file and sent pull request. Hope you understand
